sudo: true
language: ruby
rvm:
  - 2.3.4
before_install: 
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps
  - gem install bundler -v 1.15.3
